ALTER TABLE player_profiles
  ADD COLUMN name VARCHAR(100) NULL,
  ADD COLUMN age INT NULL,
  ADD COLUMN gender VARCHAR(20) NULL,
  ADD COLUMN phone_number VARCHAR(50) NULL,
  ADD COLUMN device_brand VARCHAR(50) NULL,
  ADD COLUMN device_model VARCHAR(50) NULL,
  ADD COLUMN device_os VARCHAR(50) NULL,
  ADD COLUMN device_os_version VARCHAR(50) NULL,
  ADD COLUMN app_version VARCHAR(50) NULL,
  ADD COLUMN points INT NOT NULL DEFAULT 1;
