CREATE TABLE IF NOT EXISTS active_rooms (
  room_code VARCHAR(10) PRIMARY KEY,
  room_data LONGTEXT NOT NULL,
  last_activity_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
