CREATE TABLE IF NOT EXISTS players (
  player_id VARCHAR(64) PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  coins INT NOT NULL DEFAULT 0,
  matches_played INT NOT NULL DEFAULT 0,
  games_won INT NOT NULL DEFAULT 0,
  role_stats JSON DEFAULT NULL,
  customization JSON DEFAULT NULL,
  device_info TEXT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
